[package]
name = "kdump"
version = "0.1.0"
authors = ["newcomb-luke <newcomb.luke@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
flate2 = "1.0"
termcolor = "1.1"